Traceback (most recent call last):
  File "/home/pi/randomweathernow/randomweathernow.py", line 14, in <module>
    CONSUMER_KEY = config.get(sectionheader[0], 'CONSUMER_KEY')
IndexError: list index out of range
